name: Gambling
main: net.cnation.gambling.Gambling
version: 2.0.1
author: cereal, Heytherejake
description: Casino Signs and Card Decks
commands:
    game:
        description: Create and edit casino games
        usage: /<command>
    roll:
        description: Roll a random number
        usage: /<command> <low> <high>
    deck:
        description: Deal cards
        usage: /<command>
    hand:
        description: Show your hand while playing card games
        usage: /<command>
